---
output: html_document
---

## Normalization practice (Reads)

```{r exprs-norm-read0, echo=FALSE, message=FALSE, warning=FALSE}
library(scRNA.seq.funcs)
library(scater)
library(scran)
options(stringsAsFactors = FALSE)
set.seed(1234567)
library(knitr)
opts_chunk$set(cache= TRUE, out.width='90%', fig.align = 'center', echo=FALSE)
reads <- readRDS("data/tung/reads.rds")
reads.qc <- reads[rowData(reads)$use, colData(reads)$use]
endog_genes <- !rowData(reads.qc)$is_feature_control
```

```{r exprs-norm-read1, fig.cap = "PCA plot of the tung data"}
tmp <- runPCA(
  reads.qc[endog_genes, ],
  exprs_values = "logcounts_raw"
)
plotPCA(
    tmp,
    colour_by = "batch",
    size_by = "total_features_by_counts",
    shape_by = "individual"
)
```

```{r exprs-norm-read2, fig.cap = "PCA plot of the tung data after CPM normalisation"}
logcounts(reads.qc) <- log2(calculateCPM(reads.qc, use_size_factors = FALSE) + 1)
plotPCA(
    reads.qc[endog_genes, ],
    colour_by = "batch",
    size_by = "total_features_by_counts",
    shape_by = "individual"
)
```
```{r exprs-norm-read3, fig.cap = "Cell-wise RLE of the tung data", warning=FALSE}
plotRLE(
    reads.qc[endog_genes, ], 
    exprs_values = "logcounts_raw",
    colour_by = "batch"
)
plotRLE(
    reads.qc[endog_genes, ], 
    exprs_values = "logcounts",
    colour_by = "batch"
)
```

```{r exprs-norm-read4, fig.cap = "PCA plot of the tung data after LSF normalisation"}
qclust <- quickCluster(reads.qc, min.size = 30)
reads.qc <- computeSumFactors(reads.qc, sizes = 15, clusters = qclust)
reads.qc <- normalize(reads.qc)
plotPCA(
    reads.qc[endog_genes, ],
    colour_by = "batch",
    size_by = "total_features_by_counts",
    shape_by = "individual"
)
```

```{r exprs-norm-read5, fig.cap = "Cell-wise RLE of the tung data"}
plotRLE(
    reads.qc[endog_genes, ], 
    exprs_values = "logcounts_raw",
    colour_by = "batch"
)
plotRLE(
    reads.qc[endog_genes, ], 
    exprs_values = "logcounts",
    colour_by = "batch"
)
```

```{r exprs-norm-read6, fig.cap = "PCA plot of the tung data after downsampling"}
logcounts(reads.qc) <- log2(Down_Sample_Matrix(counts(reads.qc)) + 1)
plotPCA(
    reads.qc[endog_genes, ],
    colour_by = "batch",
    size_by = "total_features_by_counts",
    shape_by = "individual"
)
```
```{r exprs-norm-read7, fig.cap = "Cell-wise RLE of the tung data"}
plotRLE(
    reads.qc[endog_genes, ], 
    exprs_values = "logcounts_raw",
    colour_by = "batch"
)
plotRLE(
    reads.qc[endog_genes, ], 
    exprs_values = "logcounts",
    colour_by = "batch"
)
```

```{r exprs-norm-read8}
reads.qc <- getBMFeatureAnnos(
    reads.qc,
    filters = "ensembl_gene_id", 
    attributes = c(
        "ensembl_gene_id",
        "hgnc_symbol",
        "chromosome_name",
        "start_position",
        "end_position"
    ), 
    biomart = "ENSEMBL_MART_ENSEMBL", 
    dataset = "hsapiens_gene_ensembl",
    host = "www.ensembl.org"
)
```

```{r exprs-norm-read9}
reads.qc.ann <- reads.qc[!is.na(rowData(reads.qc)$ensembl_gene_id), ]
```

```{r exprs-norm-read10}
eff_length <- 
    abs(rowData(reads.qc.ann)$end_position - rowData(reads.qc.ann)$start_position) / 1000
```

```{r exprs-norm-read11}
tpm(reads.qc.ann) <- log2(calculateTPM(reads.qc.ann, eff_length) + 1)
```

```{r exprs-norm-read12, fig.cap = "PCA plot of the tung data after TPM normalisation"}
tmp <- runPCA(
  reads.qc.ann,
  exprs_values = "tpm",
)
plotPCA(
    tmp,
    colour_by = "batch",
    size_by = "total_features_by_counts",
    shape_by = "individual"
)
```

```{r exprs-norm-read13}
tpm(reads.qc.ann) <- log2(calculateFPKM(reads.qc.ann, eff_length) + 1)
```

```{r exprs-norm-read14, fig.cap = "PCA plot of the tung data after FPKM normalisation", eval=FALSE}
tmp <- runPCA(
  reads.qc.ann,
  exprs_values = "tpm",
)
plotPCA(
    tmp,
    colour_by = "batch",
    size_by = "total_features_by_counts",
    shape_by = "individual"
)
```

```{r exprs-norm-read15}
sessionInfo()
```

