---
output: html_document
---

## Expression QC (Reads)

```{r exprs-qc-reads0, echo=FALSE}
library(knitr)
opts_chunk$set(cache = TRUE, out.width='90%', fig.align = 'center')
```

```{r exprs-qc-reads1, message=FALSE, warning=FALSE}
library(SingleCellExperiment)
library(scater)
options(stringsAsFactors = FALSE)
```

```{r exprs-qc-reads2}
reads <- read.table("data/tung/reads.txt", sep = "\t")
anno <- read.table("data/tung/annotation.txt", sep = "\t", header = TRUE)
```

```{r exprs-qc-reads3}
head(reads[ , 1:3])
head(anno)
```

```{r exprs-qc-reads4}
reads <- SingleCellExperiment(
    assays = list(counts = as.matrix(reads)), 
    colData = anno
)
```

```{r exprs-qc-reads5}
keep_feature <- rowSums(counts(reads) > 0) > 0
reads <- reads[keep_feature, ]
```

```{r exprs-qc-reads6}
isSpike(reads, "ERCC") <- grepl("^ERCC-", rownames(reads))
isSpike(reads, "MT") <- rownames(reads) %in% 
    c("ENSG00000198899", "ENSG00000198727", "ENSG00000198888",
    "ENSG00000198886", "ENSG00000212907", "ENSG00000198786",
    "ENSG00000198695", "ENSG00000198712", "ENSG00000198804",
    "ENSG00000198763", "ENSG00000228253", "ENSG00000198938",
    "ENSG00000198840")
```

```{r exprs-qc-reads7}
reads <- calculateQCMetrics(
    reads,
    feature_controls = list(
        ERCC = isSpike(reads, "ERCC"), 
        MT = isSpike(reads, "MT")
    )
)
```

```{r exprs-qc-reads8, fig.cap = "Histogram of library sizes for all cells"}
hist(
    reads$total_counts,
    breaks = 100
)
abline(v = 1.3e6, col = "red")
```

```{r exprs-qc-reads9}
filter_by_total_counts <- (reads$total_counts > 1.3e6)
```

```{r exprs-qc-reads10}
table(filter_by_total_counts)
```

```{r exprs-qc-reads11, fig.cap = "Histogram of the number of detected genes in all cells"}
hist(
    reads$total_features_by_counts,
    breaks = 100
)
abline(v = 7000, col = "red")
```

```{r exprs-qc-reads12}
filter_by_expr_features <- (reads$total_features_by_counts > 7000)
```

```{r exprs-qc-reads13}
table(filter_by_expr_features)
```

```{r exprs-qc-reads14, fig.cap = "Percentage of counts in MT genes"}
plotColData(
    reads,
    x = "total_features_by_counts",
    y = "pct_counts_MT",
    colour = "batch"
)
```

```{r exprs-qc-reads15, fig.cap = "Percentage of counts in ERCCs"}
plotColData(
    reads,
    x = "total_features_by_counts",
    y = "pct_counts_ERCC",
    colour = "batch"
)
```

```{r exprs-qc-reads16}
filter_by_ERCC <- 
    reads$batch != "NA19098.r2" & reads$pct_counts_ERCC < 25
table(filter_by_ERCC)
filter_by_MT <- reads$pct_counts_MT < 30
table(filter_by_MT)
```

```{r exprs-qc-reads17}
reads$use <- (
    # sufficient features (genes)
    filter_by_expr_features &
    # sufficient molecules counted
    filter_by_total_counts &
    # sufficient endogenous RNA
    filter_by_ERCC &
    # remove cells with unusual number of reads in MT genes
    filter_by_MT
)
```

```{r exprs-qc-reads18}
table(reads$use)
```

```{r exprs-qc-reads19, fig.align='center', fig.cap="PCA plot used for automatic detection of cell outliers", message=FALSE, warning=FALSE, out.width='90%'}
reads <- runPCA(
    reads,
    use_coldata = TRUE, 
    detect_outliers = TRUE
)
reducedDimNames(reads)
```

```{r exprs-qc-reads20}
table(reads$outlier)
```

```{r exprs-qc-reads21}
plotReducedDim(
    reads,
    use_dimred = "PCA_coldata",
    size_by = "total_features_by_counts", 
    shape_by = "use", 
    colour_by = "outlier"
)
```

```{r exprs-qc-reads22, fig.cap = "Comparison of the default, automatic and manual cell filters"}
library(limma)
auto <- colnames(reads)[reads$outlier]
man <- colnames(reads)[!reads$use]
venn.diag <- vennCounts(
    cbind(colnames(reads) %in% auto,
    colnames(reads) %in% man)
)
vennDiagram(
    venn.diag,
    names = c("Automatic", "Manual"),
    circle.col = c("blue", "green")
)
```

```{r exprs-qc-reads23, fig.cap = "Number of total counts consumed by the top 50 expressed genes", fig.asp = 1}
plotHighestExprs(reads, exprs_values = "counts")
```

```{r exprs-qc-reads24}
keep_feature <- nexprs(
  reads[,colData(reads)$use], 
  byrow = TRUE, 
  detection_limit = 1
) >= 2
rowData(reads)$use <- keep_feature
```

```{r exprs-qc-reads25}
table(keep_feature)
```

```{r exprs-qc-reads26}
dim(reads[rowData(reads)$use, colData(reads)$use])
```

```{r exprs-qc-reads27}
assay(reads, "logcounts_raw") <- log2(counts(reads) + 1)
reducedDim(reads) <- NULL
```

```{r exprs-qc-reads28}
saveRDS(reads, file = "data/tung/reads.rds")
```

By comparing Figure \@ref(fig:cell-filt-comp) and Figure \@ref(fig:cell-filt-comp-reads), it is clear that the reads based filtering removed more cells than the UMI based analysis. If you go back and compare the results you should be able to conclude that the ERCC and MT filters are more strict for the reads-based analysis.

```{r exprs-qc-reads29}
sessionInfo()
```
